#!/bin/bash

NC=`which nc 2>/dev/null`

if [ "$NC" == "" ] ; then
	echo "Must have netcat!"
	exit
fi

HOST="localhost"
PORT="2421"

if [ ! -z $1 ] ; then
	HOST=$1
fi
if [ ! -z $2 ] ; then
	PORT=$2
fi

echo "Welcome to netmon"
echo -n "> "
while read cmd
do
	if [ "$cmd" == "quit" ] ; then
		exit
	fi

	if [ "$cmd" == "" ] ; then
		echo -n "> "
		continue;
	fi

	echo $cmd | nc $HOST $PORT
	echo -n "> "
done
